### ISSUE TITLE
为什么在表情识别中，神经网络的accuracy如此之低呢？

### ISSUE THREAD

**Issue by younghojan** [QiushiSun/Statistical-Methods-and-Machine-Learning#1]
试了 ResNet、SVM、Kmeans，表情分类任务的accuracy都不超过 0.3，所以是为什么呢？求解！

**Comment by QiushiSun** [comment]
我们当时也讨论过这个问题，得出的结论是图片的像素很低，而且样本量小导致的，其实肉眼看也不是很好分辨表情
实验了一下数据增强也没什么用

**Comment by younghojan** [comment]
> 我们当时也讨论过这个问题，得出的结论是图片的像素很低，而且样本量小导致的，其实肉眼看也不是很好分辨表情 实验了一下数据增强也没什么用

感谢学长回复！
